name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # branche sur laquelle tu veux déclencher le workflow
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js 18
      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Build Angular en production
      - name: Build Angular
        run: npm run build -- --configuration production

      # 5. Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build et Push de l'image Docker
      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/project_angular:latest
